apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: larak8s
  name: laravel
spec:
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: husseinferas/laravel:v5
        ports:
        - containerPort: 80
