kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: larak8s
  name: laravel-claim
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
